[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[template]
  [template.environment]
    NEXT_PUBLIC_ADMIN_PIN = "Your secret PIN for the admin panel (e.g. 123456)"
